# Generated by Django 3.2.6 on 2021-08-07 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enterprise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=100)),
                ('nameC', models.CharField(max_length=100)),
                ('descrip', models.CharField(max_length=1000)),
                ('uni_code', models.IntegerField()),
                ('adress', models.CharField(max_length=1000)),
                ('phone', models.CharField(max_length=1000)),
            ],
        ),
    ]
