# Generated by Django 3.2.6 on 2021-08-07 02:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_enterprise'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enterprise',
            name='uid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contacts.users'),
        ),
    ]
