# Generated by Django 3.2.6 on 2021-08-07 03:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0003_alter_enterprise_uid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enterprise',
            old_name='uid',
            new_name='owner_id',
        ),
    ]
