# Generated by Django 3.2.6 on 2021-08-07 03:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0004_rename_uid_enterprise_owner_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enterprise',
            old_name='uni_code',
            new_name='price',
        ),
    ]
